### ISSUE TITLE
X-Forwarded-For grabbing last IP in array when need first

### ISSUE THREAD

**Issue by cdenneen** [gnif/mod_rpaf#22]
So for example here is a XFF header:

64.134.184.93, 10.148.207.91, 63.148.207.152, 209.48.37.167

We'd want 64.134.184.93 but mod_rpaf is putting 209.48.37.167 in log

**Comment by pkamps** [comment]
I have the same problem, for me it would be better to have the first IP in the X-Forwarded-For header as the new remote IP.

In my case, akamai is not sending the 'True-Client-IP' header. Maybe thats a configuration I could enable.

**Comment by gnif** [comment]
@pkamps: You are asking to break standards and make this module insecure, making is possible to spoof your client IP address. This wont be changed, you need to chase Akamai if they are not sending a header.

**Comment by pkamps** [comment]
I found out that the 'True-Client-Ip' header is something you have to enable in the akamai configuration. So I'm good.

**Comment by cdenneen** [comment]
@gnif I'm not sure I follow how this is subjective. Since standard is first IP in XFF is real client and rest are proxies then you'd think the first would be the client all the time rather than the last.
Also while I can understand your scenario about the Class C ... might it be beneficial to allow as an option to chose which field is grabbed? So for some people wanting first IP or last IP or maybe second IP? Just a thought as FR. But for now I can make use of the True-Client-IP in the new Akamai configuration setup to get around this.

**Comment by gnif** [comment]
@cdenneen The issue is that the functionallity you propose should never be used, it completely breaks the security model, it is just asking for problems. Every reverse proxy & CDN I am aware of passes the client IP in a seperate header, X-Forwarded-For was never designed for this purpose and should only be used as a last resort.
