### ISSUE TITLE
Ubuntu 14.04 yada

### ISSUE THREAD

**Issue by heikobornholdt** [gnif/mod_rpaf#26]
There is no yada package available on ubuntu 14.04.

I have to download and install the package as provided in this commit: https://github.com/gnif/mod_rpaf/blob/55c8b1d8d38dbffd474c6e0f77892d083fc2a42d/README.md

Is there a reason, why you've removed this line with commit a662b751c1af8dddec98e41315a38f8fd35afbc4 ?

**Comment by gnif** [comment]
Hi,

This is because there is no longer a debian package directory so that a 
Debian maintainer can pick this up and package it for Debian/Ubuntu.

**Comment by heikobornholdt** [comment]
Hi :),

okay, but the maintainer also has to download yada via wget instead of using repositories. I would suggest to write this in the Readme.

**Comment by tersmitten** [comment]
Indeed, that would make more sense.

**Comment by tersmitten** [comment]
@gnif Is it possible that `yada` isn't even needed to compile? On Ubuntu 14.04 it seems to compile without it.

**Comment by gnif** [comment]
`yada` is there as a dependency from when I took over this project, it is not required to build the project and will be removed from the documentation.
