### ISSUE TITLE
IPv6 fallback IPv4, apache get Segmentation fault (11)

### ISSUE THREAD

**Issue by andy199310** [gnif/mod_rpaf#31]
I am using HAProxy as frontend gateway.
In my setting: All IPv6 and IPv4 will use IPv4 connect between frontend(HAProxy 1.5) and backend(apache 2.2)

When client using IPv4 to connect, everything is ok.

However, when client using IPv6 to connect, sometime it will show 502.
In the log file I found out that if client's IPv6 is longer than a number(i'm not sure the length), apache will display as follow:
```
[notice] child pid 85407 exit signal Segmentation fault (11)
```

When i change HAProxy config to use IPv6 connect between frontend and backend, everything is fine.

Sorry about my poor English and poor information. this is my first time submitting issue.
If you need more information, please tell me what information you need.

Thanks.

**Comment by gnif** [comment]
1) Please provide your mod_rpaf configuration
2) Please provide your mod_rpaf version
3) Please provide a tcpdump (headers will be enough) of the request from the reverse proxy to the apache.

**Comment by andy199310** [comment]
1) mod_rpaf configuration

```
RPAFenable On 
RPAFsethostname On
RPAFproxy_ips {MY_HAPROXY_IP}
RPAFheader X-Forwarded-For
```

2) mod_rpaf version

```
0.6_3 
https://www.freshports.org/www/mod_rpaf2/
```

3)  tcpdump

```
GET / HTTP/1.1
User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.14.0.0 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Host: www.dev
Accept: */*
X-Forwarded-For: 2001:288:3001:17:20c:29ff:fe72:74cc
nHTTP/1.1 200 OK
Date: Thu, 15 Oct 2015 07:16:55 GMT
Server: Apache
Vary: Accept-Encoding
Connection: close
Content-Type: text/html
```

Thanks!

**Comment by gnif** [comment]
This version of rpaf does not support ipv6, it is very old. Please update before reporting errors in future.
