### ISSUE TITLE
Question related to a chain of proxies IP in X-Forwarded-For

### ISSUE THREAD

**Issue by addison74** [gnif/mod_rpaf#36]
My webserver is behind 3 proxy servers. If I run phpinfo() on Apache server _SERVER["HTTP_X_FORWARDED_FOR"] header has 4 IP values. The first one is the visitor's IP, the other three are proxies IPs. 

If I set up RPAF_ProxyIPs for those 3 proxies IPs will eliminate them from X-Forwarded-For header leaving only visitor's IP, or will eliminate only the last IP? I installed mod_rpaf Debian package and it is not working for multiple IPs only for two. I read articles about some modifications inside mod_rpaf.c file for dealing with a chain of IPs. Is your default file able to deal with this?

Thank you.

**Comment by robocoder** [comment]
I believe your scenario is handled in 0.7.0.

**Comment by gnif** [comment]
As @robocoder stated, this is handled, the first IP on the list is used. Please note though that it is much better to set the visitors real IP in a separate header on the first reverse proxy and configure mod_rpaf to use this instead, that way the `X-Forwarded-For` chain can't confuse things.
