### ISSUE TITLE
RPAFproxy_ips seems to fail on CIDR notation

### ISSUE THREAD

**Issue by pille** [gnif/mod_rpaf#38]
i'm using this on ubuntu-12.04 and it seems to fail on CIDR notation, since it's not working with

```
RPAFproxy_ips 10.10.0.0/16
```

but 

```
RPAFproxy_ips 10.10.1.1 10.10.2.2
```

**Comment by tersmitten** [comment]
We use CIDR notation too. Let me check if it also fails for us.

What version are you using?

**Comment by pille** [comment]
libapache2-mod-rpaf_0.6-2ubuntu1_amd64.deb

**Comment by tersmitten** [comment]
That's the default version from the Ubuntu repository isn't it. That version is old and not maintained by @gnif. I suggest building a newer version and using that one:

```
make && make mod_rpaf.so;
```

**Comment by gnif** [comment]
Closing this issue as 0.6 does not support CDIR, please update to 0.7 or later for this feature.
