### ISSUE TITLE
%h and %a in apache log show proxy IP, not X-Forwarded-For, but %{X-Forwarded-For}i works correctly

### ISSUE THREAD

**Issue by archon810** [gnif/mod_rpaf#47]
Hi,

I have the following setup:
OpenSUSE 42.1 with rpaf 0.8.4~rc3 (installed via package manager, so it's slightly out of date - curious if this was potentially fixed in newer releases).
CloudFlare -> nginx:80 -> apache:8080.

In this scenario, when I access something on the server, %h is the CloudFlare server's IP, but both %a and %{X-Forwarded-For}i are the real client IP. So this works.

But if I access the server on port 8080, meaning Cloudflare -> apache:8080, a really weird thing happens. %h and %a both end up with CF's IPs, but %{X-Forwarded-For}i shows the correct client IP, even though that's what RPAF was supposed to be grabbing the value from and stuffing it into %a.

Log format (for testing):
`LogFormat "Whost:%{Host}i Rhost:%h Rhost2:%a X-F-F:%{X-Forwarded-For}i %l %u Time:%t \
Req:\"%r\" Status:%>s Size:%b Ref:\"%{Referer}i\" UA:\"%{User-Agent}i\""  proxy`

Sample log lines:
`Whost:HOST_HERE Rhost:127.0.0.1 Rhost2:69.181.XX.XX(MY_REAL_CLIENT_IP) X-F-F:69.181.XX.XX(MY_REAL_CLIENT_IP) - - Time:[03/Jan/2017:23:32:32 -0800] Req:"GET /theheaders.php HTTP/1.0" Status:200...`

`Whost:HOST_HERE:8080 Rhost:162.158.255.113 Rhost2:162.158.255.113 X-F-F:69.181.XX.XX(MY_REAL_CLIENT_IP) - - Time:[03/Jan/2017:23:31:22 -0800] Req:"GET /theheaders.php HTTP/1.1" Status:200..."
`

Looking at this test page that just dumps all headers, I can correctly see X-Forwarded-For set my same correct client IP. The only difference I can see is when accessing apache on port 8080 directly, `Connection: Keep-Alive`, but when nginx 80 -> apache 8080, it's `Connection: close`.

Any ideas?

**Comment by gnif** [comment]
Please provide your mod_rpaf configuration and relevant portions of the nginx configuration.

**Comment by archon810** [comment]
mod_rpaf is very simple and default:

```<IfModule mod_rpaf.c>
    RPAF_Enable On
    RPAF_SetHostName On
    RPAF_ProxyIPs 127.0.0.1 ::1
    RPAF_Header X-Forwarded-For
```

Doh, I think it's the ProxyIPs. I'll need to drop the ones from https://support.cloudflare.com/hc/en-us/articles/200170706-How-do-I-restore-original-visitor-IP-with-Nginx- here. Let me try that. This explains why proxying through nginx which is localhost works.

**Comment by archon810** [comment]
Boom, that did it. Thanks for making me think about it once again and arrive at the conclusion almost immediately. Sometimes the brain needs a little shake.

If anyone finds this in the future, here's the fix:
`RPAF_ProxyIPs 127.0.0.1 ::1 103.21.244.0/22 103.22.200.0/22 103.31.4.0/22 104.16.0.0/12 108.162.192.0/18 131.0.72.0/22 141.101.64.0/18 162.158.0.0/15 172.64.0.0/13 173.245.48.0/20 188.114.96.0/20 190.93.240.0/20 197.234.240.0/22 198.41.128.0/17 199.27.128.0/21 2400:cb00::/32 2606:4700::/32 2803:f800::/32 2405:b500::/32 2405:8100::/32 2c0f:f248::/32 2a06:98c0::/29`

**Comment by gnif** [comment]
You're welcome :)
