### ISSUE TITLE
wildcard mask of 10.0.0.0/8 does not translate to proper ip addresses

### ISSUE THREAD

**Issue by arabek** [gnif/mod_rpaf#48]
Unless i set a specific loadbalancer ip in the config file via:
RPAFproxy_ips
The resolved ip is always the ip of the loadbalancer even though it's in the proper 10.x.x.x subnet.
After adding the ip of the loadbalancer directly (without a subnet mask) the logfile shows the proper external ip.

**Comment by gnif** [comment]
What version of mod_rpaf, and what is your config?

That setting looks like it is from mod_rpaf 0.6

**Comment by arabek** [comment]
```
# dpkg --list | grep rpaf
ii  libapache2-mod-rpaf                        0.6-2ubuntu1                                        module for Apache2 which takes the last IP from the 'X-Forwarded-For' header
```
You're correct. :(

**Comment by gnif** [comment]
0.6 does not support CDIR notation, please upgrade. Closing this issue.
