### ISSUE TITLE
Could you reserve the origin data of "X-Forwarded-For"

### ISSUE THREAD

**Issue by eeliu** [gnif/mod_rpaf#55]
Hello , I am a module developer of Apache . As some history problems,  I need to fetch the origin data of  "X-Forwarded-For" . 

While `strsep` polluted the `fwdvalue` 
```
Before 
fwdvalue = "1.1.2.2,3.4.4.4,5.6.6.6"
After 
fwdvalue = "1.1.2.2"
```
@gnif  https://github.com/gnif/mod_rpaf/blob/669c3d2ba72228134ae5832c8cf908d11ecdd770/mod_rpaf.c#L294

**Comment by gnif** [comment]
No, because this would be completely invalid and would allow spoofing of source IP addresses. If you need to specify an exact IP set the X-Real-IP header.
