### ISSUE TITLE
httpd restart error

### ISSUE THREAD

**Issue by dfnoname** [gnif/mod_rpaf#57]
after install mod_rpaf and restart httpd show this error.

Stopping httpd:                                            [  OK  ]
Starting httpd: httpd: Syntax error on line 230 of /etc/httpd/conf/httpd.conf: Syntax error on line 1 of /etc/httpd/conf.d/mod_rpaf.conf: Cannot load /etc/httpd/modules/mod_rpaf.so into server: /etc/httpd/modules/mod_rpaf.so: undefined symbol: ap_log_rerror_

**Comment by gnif** [comment]
How do you expect to get help if you do not show your configuration?

**Comment by dfnoname** [comment]
i'm just add X-real-ip.
i don't know about this issue but after i use version 0.6 it's work and my apache version is 2.2, maybe mod_rpaf version 0.8.5 is only for apache 2.4

**Comment by gnif** [comment]
Again, please show your configuration, I can not help if you do not.

**Comment by dfnoname** [comment]
```
LoadModule rpaf_module modules/mod_rpaf.so

<IfModule mod_rpaf.c>
  RPAF_Enable       On
  RPAF_ProxyIPs     127.0.0.1
  RPAF_Header       X-Real-Ip
  RPAF_SetHostName  On
  RPAF_SetHTTPS     On
  RPAF_SetPort      On
</IfModule>
```

look i'm just set X-Real-Ip

**Comment by gnif** [comment]
Sorry I just noted you stated you are running apache 2.2, you are correct, 2.2 is not supported.
