### ISSUE TITLE
when RPAF_SetHTTPS is on, rpaf doesn't replace ip address

### ISSUE THREAD

**Issue by gbouthenot** [gnif/mod_rpaf#59]
When using
```
RPAF_SetHTTPS           Off
```
Everything is fine, but if I enable it. Some connection are ok, and soon, ip address is no longer replaced with the real ip. I have to wait some seconds, then it works again and immediately fails again.
When it fails, i checked in php, I have :
_SERVER["REMOTE_ADDR"] = 10.249.2.2
_SERVER["HTTP_X_FORWARDED_FOR"] = (my ip address)
So it should be replaced but it is not.

Configuration:
```
Ubuntu 12.04 (docker image)
RPAF_ProxyIPs  10.249.0.0/16
```

**Comment by gnif** [comment]
This module is no longer being maintained, please switch to `mod_remoteip`

**Comment by chrko** [comment]
@gnif I would suggest to archive this repository, so every one knows that this isn't maintained anymore.

**Comment by Smankusors** [comment]
> This module is no longer being maintained, please switch to `mod_remoteip`

hmm that's unfortunate.., I think we need a documentation for migrating config from `mod_rpaf` to `mod_remoteip` 🤔
